### ISSUE TITLE
What if the file already exists?

### ISSUE THREAD

**Issue by christopher-francisco** [vancluever/ssh_keygen#2]
Documentation indicates only action `:create` is supported, but what if the file already exists. Will it ignore it or overwrite it with a new one?

**Comment by vancluever** [comment]
Hey @chris-fa, the behaviour is to ignore. Note that this will not show up properly 100% in a dry run right now because I forgot to add `converge_by` - my bad! I'll add it at some point in time soon, but in the meantime yeah, the resource does not overwrite. Check out https://github.com/vancluever/ssh_keygen/blob/master/lib/ssh_keygen.rb#L49 for the relevant line.

**Comment by vancluever** [comment]
Closing as this repository is getting archived.
